# Zjazd 3, część 1 — NumPy
**Autor:** [Mateusz Kozieł]

In [25]:
import numpy as np

In [26]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [27]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [30]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [31]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [32]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


Ćwiczenie 2: Indeksowanie i slicing (20 min)


In [33]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [34]:
print("Styczeń:", miesiace_sprzedaz[0])

Styczeń: 120


In [35]:
print("Grudzień:", miesiace_sprzedaz[-1])

Grudzień: 221


In [36]:
print("Q1:", miesiace_sprzedaz[0:3])

Q1: [120 135  98]


In [37]:
print("Q4:", miesiace_sprzedaz[-3:])

Q4: [143 198 221]


In [38]:
print("Co drugi miesiąc:", miesiace_sprzedaz[::2])

Co drugi miesiąc: [120  98 167 201 156 198]


In [40]:
print("Od tyłu:", miesiace_sprzedaz[::-1])

Od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


Część B — Macierz 2D

In [41]:
import numpy as np

dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])

produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [42]:
print("B1:", dane[0, 1])

B1: 145


In [43]:
print("B2:", dane[2])

B2: [234 267 289]


In [44]:
print("B3:", dane[:, 0])

B3: [120  89 234  56]


In [45]:
print("B4:", dane[1:3, 1:3])

B4: [[102  95]
 [267 289]]


Ćwiczenie 3: Operacje wektorowe — analiza biznesowa (25 min)


In [46]:
import numpy as np

nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

nazwy = np.array(nazwy)

## Zadanie 1 — Podstawowe statystyki cenowe

In [47]:
srednia_cena = ceny.mean()
najdrozszy_idx = ceny.argmax()
najtanszy_idx = ceny.argmin()

print(f"Średnia cena: {srednia_cena:.1f} zł")
print(f"Najdroższy produkt: {nazwy[najdrozszy_idx]} ({ceny[najdrozszy_idx]} zł)")
print(f"Najtańszy produkt: {nazwy[najtanszy_idx]} ({ceny[najtanszy_idx]} zł)")

Średnia cena: 1171.0 zł
Najdroższy produkt: Laptop (3499 zł)
Najtańszy produkt: Ładowarka (89 zł)


## Zadanie 2 — Wartość magazynu

In [48]:
wartosci = ceny * ilosci_magazyn
laczna_wartosc = wartosci.sum()

print("Wartość każdego produktu:", wartosci)
print(f"Łączna wartość magazynu: {laczna_wartosc} zł")

Wartość każdego produktu: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465 zł


## Zadanie 3 — Analiza cenowa

In [49]:
ceny_po_rabacie = ceny * 0.85
ceny_z_vat = ceny * 1.23
produkty_powyzej_1000 = (ceny > 1000).sum()

print("Ceny po rabacie 15%:", ceny_po_rabacie)
print("Ceny z VAT 23%:", ceny_z_vat)
print(f"Ile produktów kosztuje powyżej 1000 zł: {produkty_powyzej_1000}")

Ceny po rabacie 15%: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z VAT 23%: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Ile produktów kosztuje powyżej 1000 zł: 4


## Zadanie 4 — Filtrowanie

In [50]:
maska_oceny = oceny_klientow >= 4.5
print("Produkty z oceną >= 4.5:")
print("Nazwy:", nazwy[maska_oceny])
print("Ceny:", ceny[maska_oceny])

maska_tanie = ceny < 200
print("\nProdukty poniżej 200 zł:")
print("Nazwy:", nazwy[maska_tanie])
print("Ilości w magazynie:", ilosci_magazyn[maska_tanie])

Produkty z oceną >= 4.5:
Nazwy: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]

Produkty poniżej 200 zł:
Nazwy: ['Ładowarka' 'Mysz']
Ilości w magazynie: [312 201]


## Zadanie 5 — Analiza zapasów

In [51]:
maska_niski_stan = ilosci_magazyn < 30

niskie_produkty = nazwy[maska_niski_stan]
wartosc_niskich = wartosci[maska_niski_stan].sum()
procent_magazynu = (wartosc_niskich / laczna_wartosc) * 100

print("Produkty z niskim stanem magazynowym (<30):", niskie_produkty)
print(f"Łączna wartość tych produktów: {wartosc_niskich} zł")
print(f"Ile % całego magazynu stanowią: {procent_magazynu:.2f}%")

Produkty z niskim stanem magazynowym (<30): ['Laptop' 'Monitor']
Łączna wartość tych produktów: 86962 zł
Ile % całego magazynu stanowią: 15.83%


## Zadanie 6 — Bonus: analiza cena–ocena

In [52]:
maska_okazje = (oceny_klientow >= 4.5) & (ceny < 1000)

print("Produkty będące okazją:")
print("Nazwy:", nazwy[maska_okazje])
print("Ceny:", ceny[maska_okazje])

srednia_ge_4 = ceny[oceny_klientow >= 4.0].mean()
srednia_lt_4 = ceny[oceny_klientow < 4.0].mean()

print(f"\nŚrednia cena produktów z oceną >= 4.0: {srednia_ge_4:.2f} zł")
print(f"Średnia cena produktów z oceną < 4.0: {srednia_lt_4:.2f} zł")

Produkty będące okazją:
Nazwy: ['Słuchawki']
Ceny: [349]

Średnia cena produktów z oceną >= 4.0: 1446.14 zł
Średnia cena produktów z oceną < 4.0: 529.00 zł


Ćwiczenie 4: Benchmark — lista vs NumPy (15 min)


In [53]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  94.4 ms
NumPy:  2.5 ms
NumPy jest 37× szybszy!


In [54]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  12.0 ms
NumPy:  2.0 ms
NumPy jest 6× szybszy!


In [55]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  54.1 ms
NumPy:  3.3 ms
NumPy jest 17× szybszy!


## Wnioski z benchmarku

- NumPy jest **37x** szybszy w mnożeniu
- NumPy jest **6x** szybszy w sumowaniu
- NumPy jest **17x** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list