# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** [Mateusz Kozieł]

In [1]:
import numpy as np

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.

In [3]:
ceny_inflacja = ceny * 1.05
print(ceny_inflacja)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.



In [5]:
rabaty = np.array([0.10, 0.05, 0.15])

ceny_rabat = ceny * (1 - rabaty)
print(ceny_rabat)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%.



In [6]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])

koszt = ceny / (1 + marza)
print(koszt)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.



In [8]:
indeksy = ceny.argmin(axis=1)

najtansze_sklepy = [sklepy[i] for i in indeksy]

for produkt, sklep in zip(produkty, najtansze_sklepy):
    print(f"Produkt {produkt}: {sklep}")

Produkt A: Online
Produkt B: Online
Produkt C: Online
Produkt D: Online


Ćwiczenie 2: Reshape i łączenie danych (20 min)


Zadanie 2a — Reshape

In [9]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b - Stacking

In [10]:
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)


In [11]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

sprzedaz = sprzedaz_flat.reshape(6, 2)
print(f"Macierz 6x2:\n{sprzedaz}")

srednia_per_produkt = sprzedaz.mean(axis=1)
print(f"Średnia sprzedaż per produkt: {srednia_per_produkt}")

zmiana = sprzedaz[:, 1] - sprzedaz[:, 0]
print(f"Zmiana między miesiącem 1 a 2: {zmiana}")

Macierz 6x2:
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia sprzedaż per produkt: [150. 225. 215. 170. 240. 225.]
Zmiana między miesiącem 1 a 2: [100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [12]:
wektor = kwartaly.flatten()
print(f"Spłaszczony wektor: {wektor}")

nowy_wektor = np.concatenate([wektor, np.array([235])])
print(f"Po dodaniu 13. miesiąca: {nowy_wektor}")
print(f"Długość nowej tablicy: {len(nowy_wektor)}")

Spłaszczony wektor: [120 135  98 142 167 189 201 178 156 143 198 221]
Po dodaniu 13. miesiąca: [120 135  98 142 167 189 201 178 156 143 198 221 235]
Długość nowej tablicy: 13


Ćwiczenie 3: Analiza danych finansowych (30 min)


In [13]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a: Analiza wynagrodzeń



In [15]:
srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()
pracownicy = np.array(pracownicy)

print("Średnia:", srednia)
print("Mediana:", mediana)
print("Odchylenie:", odchylenie)

print("Powyżej średniej:", pracownicy[pensje > srednia])
print("Poniżej mediany:", pracownicy[pensje < mediana])

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("Rozstęp:", rozstep)
print("IQR:", iqr)

Średnia: 6425.0
Mediana: 6050.0
Odchylenie: 1616.9029037020127
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900
IQR: 2200.0


Zadanie 3b: System premii (np.where)



In [16]:
premie = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

nowe_pensje = pensje + premie

print("Premie:", premie)
print("Nowe pensje:", nowe_pensje)

najwieksza_premia = pracownicy[premie.argmax()]
print("Najwyższa premia:", najwieksza_premia)

Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższa premia: Ewa


Zadanie 3c: Ranking (argsort)



In [17]:
kolejnosc = np.argsort(pensje)[::-1]

for i, idx in enumerate(kolejnosc, 1):
    print(f"{i}. {pracownicy[idx]} — {pensje[idx]} zł, staż: {staz[idx]} lat")

1. Marek — 9100 zł, staż: 15 lat
2. Zofia — 8500 zł, staż: 12 lat
3. Jan — 7200 zł, staż: 8 lat
4. Kasia — 6300 zł, staż: 5 lat
5. Tomek — 5800 zł, staż: 4 lat
6. Anna — 5500 zł, staż: 3 lat
7. Ewa — 4800 zł, staż: 2 lat
8. Piotr — 4200 zł, staż: 1 lat


Zadanie 3d: Korelacja



In [18]:
korelacja_staz_pensje = np.corrcoef(staz, pensje)[0, 1]
korelacja_staz_oceny = np.corrcoef(staz, oceny)[0, 1]

print("Korelacja staż-pensja:", korelacja_staz_pensje)
print("Korelacja staż-oceny:", korelacja_staz_oceny)

if abs(korelacja_staz_pensje) > abs(korelacja_staz_oceny):
    print("Silniejszy związek: staż-pensja")
else:
    print("Silniejszy związek: staż-oceny")

Korelacja staż-pensja: 0.987862864584301
Korelacja staż-oceny: 0.04198471605953068
Silniejszy związek: staż-pensja


Zadanie 3e: Analiza sprzedaży (broadcasting)



In [19]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

print("Przychód:\n", przychod)

# najlepszy produkt
najlepszy_produkt = produkty_nazwy[przychod.sum(axis=1).argmax()]
print("Najlepszy produkt:", najlepszy_produkt)

# najlepszy miesiąc
najlepszy_miesiac = przychod.sum(axis=0).argmax() + 1
print("Najlepszy miesiąc:", najlepszy_miesiac)

# trend
pierwsze_3 = przychod[:, :3].sum()
ostatnie_3 = przychod[:, 3:].sum()

print("Pierwsze 3 miesiące:", pierwsze_3)
print("Ostatnie 3 miesiące:", ostatnie_3)

Przychód:
 [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Najlepszy produkt: Smartfon
Najlepszy miesiąc: 2
Pierwsze 3 miesiące: 2463950
Ostatnie 3 miesiące: 2536500


Ćwiczenie 4: Generowanie danych (15 min)


In [20]:
np.random.seed(42)

wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [21]:
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")
print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")
print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")

Wiek — średnia: 33.6, mediana: 33.0, std: 8.6, min: 18, max: 53
Wydatki — średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty — średnia: 4.9, mediana: 5.0, std: 2.2, min: 1, max: 11


In [22]:
korelacja_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
korelacja_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]

print("Korelacja wiek-wydatki:", korelacja_wiek_wydatki)
print("Korelacja wizyty-wydatki:", korelacja_wizyty_wydatki)

Korelacja wiek-wydatki: -0.12009183441777695
Korelacja wizyty-wydatki: -0.15884985147948125


In [23]:
sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(wydatki > sr + sd, "WYSOKI",
          np.where(wydatki < sr - sd, "NISKI", "ŚREDNI"))

print(segment)

['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI'
 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'NISKI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'WYSOKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'WYSOKI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI']


In [24]:
unikalne, liczby = np.unique(segment, return_counts=True)

for u, l in zip(unikalne, liczby):
    print(f"{u}: {l}")

NISKI: 17
WYSOKI: 12
ŚREDNI: 71
